server:
  port: 8090

spring:
  application:
    name: jwt_auth-flow

  datasource:
    url: jdbc:postgresql://localhost:5439/jwt_auth_flow_database
    username: username
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true
